version: "3.7"
services:
  app:
    build: .
    depends_on:
      - postgresdb
      - mongodb
    ports:
      - 3000:3000

  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: typeormdemo
    ports:
      - 35432:5432
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
